# Generated by Django 5.2 on 2025-04-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_ticket_config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketconfig",
            name="ticket_channel_id",
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ticketconfig",
            name="dc_id",
            field=models.BigIntegerField(),
        ),
    ]
