# Generated by Django 5.2 on 2025-04-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_ticket_config", "0002_ticketconfig_ticket_channel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketconfig",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticketconfig",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=10,
            ),
        ),
    ]
