# Generated by Django 5.2 on 2025-04-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "store_ticket_config",
            "0003_ticketconfig_resolved_at_alter_ticketconfig_status",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketconfig",
            name="resolved_by_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketconfig",
            name="resolved_by_username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
