# Generated by Django 5.2 on 2025-04-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_ticket_config", "0004_ticketconfig_resolved_by_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketconfig",
            name="resolved_by_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticketconfig",
            name="resolved_by_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
