apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: your-django-image:latest  # Replace with your Docker Hub image or local image
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_DB
              value: your_db_name
            - name: POSTGRES_USER
              value: your_db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: postgres  # Must match the service name you expose
